spring:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: admin
    password: urubu100
